// <auto-generated />
namespace Manga.DATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changerelationshipbetweensubjectandstudentmapthemtonewclasslinq_SubjecT_Teacher : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changerelationshipbetweensubjectandstudentmapthemtonewclasslinq_SubjecT_Teacher));
        
        string IMigrationMetadata.Id
        {
            get { return "201806112042124_change relationship between subject and student, map them to new class linq_SubjecT_Teacher"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
