// <auto-generated />
namespace Manga.DATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addreferencetotableusers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addreferencetotableusers));
        
        string IMigrationMetadata.Id
        {
            get { return "201806101254129_add reference to table users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
