// <auto-generated />
namespace Manga.DATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addstudentgradegradesteacherssubjectsprovincesgenderstableanddeletebookchapterspages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addstudentgradegradesteacherssubjectsprovincesgenderstableanddeletebookchapterspages));
        
        string IMigrationMetadata.Id
        {
            get { return "201806052016471_add student, grade, grades, teachers, subjects, provinces, genders table, and delete book, chapters, pages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
