// <auto-generated />
namespace Manga.DATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addteacheridtotablegrades : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addteacheridtotablegrades));
        
        string IMigrationMetadata.Id
        {
            get { return "201806122107550_add teacherid to table grades"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
