// <auto-generated />
namespace Manga.DATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createtableUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createtableUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201806092326072_create table User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
